<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="Assets/CSS/style.css">
    <title>deinBerichtsheft.de</title>
</head>

<body id="scrollTop" class="d-flex flex-column h-100">
    <nav class="navbar sticky-top navbar-expand-sm navbar-dark bg-primary shadow">
        <div class="container px-3">
            <a class="navbar-brand px-1" href="?controller=Report&do=showReportOverview">deinBerichtsheft.de</a>
                <?php if(isset($_SESSION["userId"])) { ?>
                    <div class="justify-content-end" id="navbarNavAltMarkup">
                        <div class="btn-group">
                          <button type="button" id="user-profile-img-nav" class="btn border-0 p-0 d-flex justify-content-center" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                            <div id="user-img-container-nav" class="d-flex justify-content-center align-items-center"> 
                                <?php if (isset($_SESSION["userImg"])): ?>   
                                    <img id="user-img-nav" class="" src="<?=$_SESSION["userImg"]?>" alt="">     
                                <?php else: ?>
                                    <img id="user-img-nav" class="" src="Uploads/user.jpg" alt="">   
                                <?php endif; ?>
                            </div>           
                          </button>
                          <ul class="dropdown-menu dropdown-menu-sm-end pt-1">
                            <li>
                                <a class="dropdown-item d-flex align-items-center px-1" href="?controller=User&do=showEditUserForm">
                                    <span class="material-icons px-1">
                                        manage_accounts
                                    </span>
                                    Profil bearbeiten
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item d-flex align-items-center px-1" href="?controller=User&do=showLogoutConfirmation">
                                    <span class="material-icons px-1 f-22-icons">
                                        logout
                                    </span>
                                    Ausloggen
                                </a>
                            </li>
                          </ul>
                        </div>
                    </div>
                <?php } ?>
        </div>
    </nav>

    <main class="flex-shrink-0">
