<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="CSS/style.css">
    <title>deinBerichtsheft.de</title>
</head>

<body class="d-flex flex-column h-100">
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary shadow">
        <div class="container px-4">
            <a class="navbar-brand" href="?controller=Welcome&do=showWelcome">deinBerichtsheft.de</a>
            <?php if(isset($_SESSION["userUid"])) { ?>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="?controller=Welcome&do=showWelcome">Willkommen</a>
                    <a class="nav-link" href="?controller=Welcome&do=showProjects">Projekte</a>
                    <a class="nav-link" href="?controller=Welcome&do=showTutorials">Tutorials</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-link" href="?controller=Welcome&do=showLogout"><?php echo $_SESSION["userName"] ?> ausloggen</a>
                </div>
            </div>
            <?php } ?>
        </div>
    </nav>

    <main class="flex-shrink-0">
