<div class="container my-4">
  <div class="row">
    <div class="col-12 col-lg-4 text-center my-2">
      <img class="bd-placeholder-img rounded-circle mb-3 shadow" src="../images/marketing/persona_azubi_1.png" width="140" height="140"></img>
      <div class="col-9 mx-auto">
        <p class="fst-italic mb-0">"Seit dem ich mein Berichtsheft online führen kann, schreibe ich es viel regelmäßiger."</p>
        <small>Maria K.</small>
      </div>
    </div>
    <div class="col-lg-4 text-center my-2">
      <img class="bd-placeholder-img rounded-circle mb-3 shadow" src="../images/marketing/persona_ausbilder.png" width="140" height="140"></img>
      <div class="col-9 mx-auto">
        <p class="fst-italic mb-0">"Für mich als Ausbilder ist es total praktisch wenn das Berichtheft online gepflegt wird."</p>
        <small>Christopher L.</small>
      </div>
    </div>
    <div class="col-lg-4 text-center my-2">
      <img class="bd-placeholder-img rounded-circle mb-3 shadow" src="../images/marketing/persona_azubi_2.png" width="140" height="140"></img>
      <div class="col-9 mx-auto">
        <p class="fst-italic mb-0">"Ich finde es super, dass ich mein Berichtheft jetzt auch auf meinem Smartphone pfelgen kann."</p>
        <small>Benjamin R.</small>
      </div>
    </div>
  </div>
</div>