<?php
include dirname(__DIR__).'/Basic/header.phtml';
?>   
<div class="container-fluid form-background shadow">
    <div class="row justify-content-center">
        <div class="col-11 col-sm-9 col-md-7 col-lg-5 col-xl-4 px-0">
            <div class="card card-start card-pwd text-start my-5 shadow">
                <div class="card-header">
                    <div class="nav nav-tabs card-header-tabs">
                        <div class="nav-item">
                            <span class="nav-link active" aria-current="true">Passwort zurücksetzen</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form id="resetPwdForm" method="post">
                        <?php foreach ($resetPwdLabels as $index => $value): ?>
                            <?php if (substr($index,4,3) == "Pwd"): ?>
                            <div class="mb-3"> 
                                <label class="form-label" for="<?=$index?>"><?=$value?></label>
                                <input type="password" class="form-control" id="<?=$index?>" name="<?=$index?>" placeholder="<?=$value?>">
                                <?php if (isset($resetPwdErrors[$index])): ?><div id="pwdlHelp" class="form-text"><?=$resetPwdErrors[$index]?></div><?php endif; ?>
                            </div>
                            <?php else: ?>
                                <input type="hidden" name="<?=$index?>" id="<?=$index?>"  value="<?=$resetPwdSecurityData[$index]?>">
                            <?php endif; ?>
                        <?php endforeach; ?>                              
                        <input type="hidden" name="controller" value="user">       
                        <input type="hidden" name="do" value="validateResetPasswordForm">
                    </form>
                </div>
                <div class="card-footer card-footer-custom">
                    <div class="col-12 text-start">
                        <a class="text-decoration-none d-flex align-items-center" href="?controller=User&do=showLoginForm">
                            <span class="material-icons fs-5 py-1 pr-1">arrow_back</span>
                            <span class="p-1">Zurück zum Login</span>
                        </a>
                    </div>  
                </div>
                <div class="card-footer text-muted">
                    <div class="col-12 text-center">
                        <input type="submit" form="resetPwdForm" class="btn btn-primary" name="submit" value="Absenden">
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
<?php include dirname(__DIR__).'/Marketing//marketing.phtml'; ?>
<?php include dirname(__DIR__).'/Basic/footer.phtml'; ?>
<?php include dirname(__DIR__).'/Includes/navbarActiveState.phtml'; ?>
<?php include dirname(__DIR__).'/Basic/footerEnd.phtml'; ?>