<?php
include dirname(__DIR__) . '/Basic/header.phtml';
?>
<div class="modal" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body row align-items-center">
        <div class="col-12 text-center">
          <div class="spinner-grow text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
          <h4 class="text-muted mt-2">E-Mail wird gesendet...</h4>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="wrapper" class="wrapper">
  <div class="outer">
    <div class="middle">
      <div class="col-12 text-center mx-auto">
        <h3 class="text-secondary px-2">
          Überprüfe dein Postfach.<br>
          Wir haben dir eine E-Mail gesendet.
        </h3>
        <a class="btn btn-primary mt-3" href="?controller=User&do=showLoginForm">Hier geht's zum Login</a>
      </div>
    </div>
  </div>
</div>
<?php include dirname(__DIR__) . '/Basic/footer.phtml'; ?>
<?php include dirname(__DIR__) . '/Includes/modalToggle.phtml'; ?>
<?php include dirname(__DIR__) . '/Basic/footerEnd.phtml'; ?>