<?php
include dirname(__DIR__) . '/Basic/header.phtml';
?>
<div class="container">
    <div class="row pt-5 px-2">
        <div class="col-12">
            <h2>
                Neuer Tagesbericht
            </h2> 
            <hr>
        </div>
        <div class="col-12 mb-5">
            <div class="card card-start card-article text-start shadow">
                <div class="card-body">
                    <form id="articleForm" method="post">
                        <?php foreach ($articleLabels as $index => $value) : ?>
                            <div class="mb-3">
                                <label class="form-label" for="<?= $index ?>"><?= $value ?></label>
                        <?php if (substr($index, 7, 9) == "Date") : ?>
                                <input type="date" class="form-control" id="<?= $index ?>" name="<?= $index ?>" value="">
                                <?php if (isset($articleErrors[$index])) : ?><div id="nameHelp" class="form-text"><?= $articleErrors[$index] ?></div><?php endif; ?>
                            </div>
                        <?php else : ?>
                            <textarea class="form-control mb-3" id="<?= $index ?>" name="<?= $index ?>" placeholder="<?= $value ?>" value="" rows="12"></textarea>
                            <?php if (isset($articleErrors[$index])) : ?><div id="descriptionHelp" class="form-text"><?= $articleErrors[$index] ?></div><?php endif; ?>
                            </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                        <input type="hidden" name="controller" value="article">
                        <input type="hidden" name="do" value="validateNewArticleForm">
                    </form>
                </div>
                <div class="card-footer d-flex justify-content-between text-muted">
                    <a href="?controller=Report&do=showReportDetail&reportId=<?= urlencode($reportId)?>&reportName=<?= urlencode($reportName)?>" class="btn btn-sm btn-outline-primary">Zurück zur Übersicht</a>
                    <input type="submit" form="articleForm" class="btn btn-sm btn-primary" name="submit" value="Bericht erstellen">
                </div>
            </div>
        </div>
    </div>
</div>
<?php include dirname(__DIR__) . '/Basic/footer.phtml'; ?>
<?php include dirname(__DIR__) . '/Includes/navbarActiveState.phtml'; ?>
<?php include dirname(__DIR__) . '/Basic/footerEnd.phtml'; ?>