<?php
include dirname(__DIR__).'/Basic/header.phtml';
?>    
<div class="container">
    <div class="row pt-5 px-2">
        <div class="col-12">
            <h2>Projekte</h2>
            <hr>
        </div> 
        <div class="col-6">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat 
                nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui 
                officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla 
                gravida orci a odio. 
            </p>
        </div>
        <div class="col-6">    
            <p>
                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna 
                lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, 
                nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. 
                Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. 
                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse 
                platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.
            </p>
        </div>
    </div>
</div>
<?php include dirname(__DIR__).'/Basic/footer.phtml'; ?>
<?php include dirname(__DIR__).'/Includes/navbarActiveState.phtml'; ?>
<?php include dirname(__DIR__).'/Basic/footerEnd.phtml'; ?>