<?php
include dirname(__DIR__) . '/Basic/header.phtml';
?>
<div class="container">
    <div class="row pt-5 px-2">
        <div class="col-12 d-flex justify-content-between align-items-center">
            <h2>
                <?= $reportName ?>
            </h2>
            <div class="d-flex justify-content-between align-items-center">
                <button id="switchCardTable" class="btn d-flex inline-items-center mr-2">
                    <span class="material-icons">
                        format_list_numbered
                    </span>
                    <span class="material-icons d-none">
                        apps
                    </span>
                </button>
                <a class="d-flex text-decoration-none" href="?controller=Report&do=showEditReportForm&reportId=<?= urlencode($reportId) ?>&reportName=<?= urlencode($reportName) ?>"><span class="material-icons text-dark">settings</span></a>
            </div>
        </div>
        <div class="col-12"><hr></div>
        <div class="col-12 mb-5">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4  g-4">
                <div class="col action">
                    <a href="?controller=Report&do=showReportOverview" class="card card-action text-dark bg-light text-decoration-none shadow">
                        <div class="card-body row h-100 align-items-center">
                            <div class="col-12 card-action-hover">
                                <h5 class="card-title text-center"><strong>Zurück zur Übersicht</strong></h5>
                                <div class="col-12 text-center"><span id="addIcon" class="material-icons py-1">article</span></div>  
                            </div>
                        </div>
                    </a>
                </div>    
                <div class="col action">
                    <a href="?controller=Article&do=showNewArticleForm&reportId=<?= urlencode($reportId) ?>&reportName=<?= urlencode($reportName) ?>" class="card card-action text-dark bg-light text-decoration-none shadow">
                        <div class="card-body row h-100 align-items-center">
                            <div class="col-12 card-action-hover">
                                <h5 class="card-title text-center"><strong>Neuer Tagesbericht</strong></h5>
                                <div class="col-12 text-center"><span id="addIcon" class="material-icons py-1">add_circle_outline</span></div>  
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col action">
                    <div  class="card card-action text-dark bg-light text-decoration-none shadow">
                        <div class="card-body row h-100 align-items-center">
                            <div class="col-12 card-action-hover">
                                <h5 class="card-title text-center mt-1"><strong>Suche nach Datum</strong></h5>
                                <input type="date" class="form-control mt-2" id="date">
                                <input type="date" class="form-control mt-1" id="date2" disabled>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col action col-placeholder">
                    <div class="card card-action border-0 bg-transparent">
                    </div>
                </div>
                <?php if (!empty($reportDetailData)) : ?>
                    <?php foreach ($reportDetailData as $index => $value) : ?>
                        <div class="col content-card">
                            <a href="?controller=Article&do=showEditArticleForm&reportId=<?= urlencode($reportId) ?>&reportName=<?= urlencode($reportName) ?>&articleId=<?= urlencode($reportDetailData[$index]["articleId"]) ?>" class="card card-action text-white bg-light text-decoration-none shadow">
                                <div class="card-header bg-primary">
                                    <h5 class="card-title card-title-date">Tagesbericht <?= date('d.m.Y',strtotime($reportDetailData[$index]["articleDate"])) ?></h5>
                                </div>
                                <div class="card-body"> 
                                    <p class="card-text text-dark mb-1"><?= substr($reportDetailData[$index]["articleText"], 0, 60)."..." ?></p>
                                </div>                           
                            </a>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div id="table-container" class="d-none w-100">
                    <table id="table" data-show-columns="true" class="table table-light table-striped shadow table-hover">
                      <thead>
                        <tr>
                          <th class="bg-primary text-white" scope="col">Datum</th>
                          <th class="bg-primary text-white" scope="col">Eintrag</th>
                        </tr>
                      </thead>
                      <tbody>
                      <?php if (!empty($reportDetailData)) : ?>
                        <?php foreach ($reportDetailData as $index => $value) : ?> 
                            <tr class="date-check">
                              <th scope="row"><a class="table-date text-decoration-none text-dark" href="?controller=Article&do=showEditArticleForm&reportId=<?= urlencode($reportId) ?>&reportName=<?= urlencode($reportName) ?>&articleId=<?= urlencode($reportDetailData[$index]["articleId"]) ?>"><?= date('d.m.Y',strtotime($reportDetailData[$index]["articleDate"])) ?></a></th>
                              <td><a class="text-decoration-none text-dark" href="?controller=Article&do=showEditArticleForm&reportId=<?= urlencode($reportId) ?>&reportName=<?= urlencode($reportName) ?>&articleId=<?= urlencode($reportDetailData[$index]["articleId"]) ?>"><?= substr($reportDetailData[$index]["articleText"], 0, 120)."..." ?></a></td>
                            </tr>
                        <?php endforeach; ?>
                      <?php endif; ?>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>    
</div>
<?php include dirname(__DIR__) . '/Basic/footer.phtml'; ?>
<?php include dirname(__DIR__) . '/Includes/navbarActiveState.phtml'; ?>
<?php include dirname(__DIR__) . '/Includes/reportDetailScript.phtml'; ?>
<?php include dirname(__DIR__) . '/Basic/footerEnd.phtml'; ?>