<?php
include dirname(__DIR__).'/header.phtml';
?>    
<div class="container">
    <div class="row pt-5">
        <div class="col-12">
            <h2>
                Eingeloggt als <?php echo $_SESSION["userName"]; ?>
            </h2>
            <a href="?controller=Welcome&do=showWelcome">Hier geht's weiter</a>
        </div>
    </div>
</div>
<?php include dirname(__DIR__).'/footer.phtml'; ?>