<?php
include dirname(__DIR__).'/Basic/header.phtml';
?>
<div class="container">
    <div class="row pt-5 px-2">
        <div class="col-12">    
            <h2><?=$error?></h2>
            <p><?=$debug?></p>
        </div>
    </div>
</div>

<?php include dirname(__DIR__).'/Basic/footer.phtml'; ?>
<?php include dirname(__DIR__).'/Includes/navbarActiveState.phtml'; ?>
<?php include dirname(__DIR__).'/Basic/footerEnd.phtml'; ?>

