<?php
include dirname(__DIR__).'/header.phtml';
?>
<div class="container-fluid form-background shadow">    
    <div class="row justify-content-center">
        <div class="col-11 col-sm-9 col-md-7 col-lg-5 col-xl-4 px-0">
            <div class="card card-start card-registration text-start my-5 shadow">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="true" href="?controller=Registration&do=showRegistrationForm">Registrierung</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="?controller=Login&do=showLoginForm">Einloggen</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <form id="registrationForm" method="post">
                        <?php foreach ($labels as $index => $value): ?>
                        <div class="mb-3">
                        <label class="form-label" for="<?=$index?>"><?=$value?></label>
                        <?php if (substr($index,4,3) == "Pwd"): ?>
                            <input type="password" class="form-control" id="<?=$index?>" name="<?=$index?>" placeholder="<?=$value?>" value="">
                            <?php if (isset($errors[$index])): ?><div id="emailHelp" class="form-text"><?=$errors[$index]?></div><?php endif; ?>
                        </div>
                        <?php elseif (substr($index,4,5) == "Email"): ?>
                            <input type="email" class="form-control" id="<?=$index?>" name="<?=$index?>" placeholder="<?=$value?>" value="">
                            <?php if (isset($errors[$index])): ?><div id="emailHelp" class="form-text"><?=$errors[$index]?></div><?php endif; ?>
                        </div>
                        <?php else: ?>
                            <input type="text" class="form-control" id="<?=$index?>" name="<?=$index?>" placeholder="<?=$value?>" value="">
                            <?php if (isset($errors[$index])): ?><div id="emailHelp" class="form-text"><?=$errors[$index]?></div><?php endif; ?>
                        </div>
                        <?php endif; ?>
                        <?php endforeach; ?>                       
                        <input type="hidden" name="controller" value="registration">       
                        <input type="hidden" name="do" value="validateForm">                
                    </form>
                </div>
                <div class="card-footer text-muted">
                    <div class="col-12 text-center">
                        <input type="submit" form="registrationForm" class="btn btn-primary" name="submit" value="Absenden">
                    </div> 
                </div>
            </div>
        </div>
    </div>
</div>
<?php include dirname(__DIR__).'/marketing.phtml'; ?>
<?php include dirname(__DIR__).'/footer.phtml'; ?>
<?php include dirname(__DIR__).'/footerEnd.phtml'; ?>